CREATE TABLE IF NOT EXISTS public.debug_stat_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    party_member_id UUID,
    member_name TEXT,
    change_source TEXT NOT NULL,
    stats JSONB NOT NULL
);

COMMENT ON TABLE public.debug_stat_changes IS 'A debug table to track stat changes for individual characters.';